// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: pkg/apis/tfserving/v1/resource_handle.proto

package tfserving

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on ResourceHandleProto with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ResourceHandleProto) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ResourceHandleProto with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ResourceHandleProtoMultiError, or nil if none found.
func (m *ResourceHandleProto) ValidateAll() error {
	return m.validate(true)
}

func (m *ResourceHandleProto) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Device

	// no validation rules for Container

	// no validation rules for Name

	// no validation rules for HashCode

	// no validation rules for MaybeTypeName

	for idx, item := range m.GetDtypesAndShapes() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ResourceHandleProtoValidationError{
						field:  fmt.Sprintf("DtypesAndShapes[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ResourceHandleProtoValidationError{
						field:  fmt.Sprintf("DtypesAndShapes[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ResourceHandleProtoValidationError{
					field:  fmt.Sprintf("DtypesAndShapes[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return ResourceHandleProtoMultiError(errors)
	}

	return nil
}

// ResourceHandleProtoMultiError is an error wrapping multiple validation
// errors returned by ResourceHandleProto.ValidateAll() if the designated
// constraints aren't met.
type ResourceHandleProtoMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ResourceHandleProtoMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ResourceHandleProtoMultiError) AllErrors() []error { return m }

// ResourceHandleProtoValidationError is the validation error returned by
// ResourceHandleProto.Validate if the designated constraints aren't met.
type ResourceHandleProtoValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ResourceHandleProtoValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ResourceHandleProtoValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ResourceHandleProtoValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ResourceHandleProtoValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ResourceHandleProtoValidationError) ErrorName() string {
	return "ResourceHandleProtoValidationError"
}

// Error satisfies the builtin error interface
func (e ResourceHandleProtoValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sResourceHandleProto.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ResourceHandleProtoValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ResourceHandleProtoValidationError{}

// Validate checks the field values on ResourceHandleProto_DtypeAndShape with
// the rules defined in the proto definition for this message. If any rules
// are violated, the first error encountered is returned, or nil if there are
// no violations.
func (m *ResourceHandleProto_DtypeAndShape) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ResourceHandleProto_DtypeAndShape
// with the rules defined in the proto definition for this message. If any
// rules are violated, the result is a list of violation errors wrapped in
// ResourceHandleProto_DtypeAndShapeMultiError, or nil if none found.
func (m *ResourceHandleProto_DtypeAndShape) ValidateAll() error {
	return m.validate(true)
}

func (m *ResourceHandleProto_DtypeAndShape) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Dtype

	if all {
		switch v := interface{}(m.GetShape()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ResourceHandleProto_DtypeAndShapeValidationError{
					field:  "Shape",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ResourceHandleProto_DtypeAndShapeValidationError{
					field:  "Shape",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetShape()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ResourceHandleProto_DtypeAndShapeValidationError{
				field:  "Shape",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return ResourceHandleProto_DtypeAndShapeMultiError(errors)
	}

	return nil
}

// ResourceHandleProto_DtypeAndShapeMultiError is an error wrapping multiple
// validation errors returned by
// ResourceHandleProto_DtypeAndShape.ValidateAll() if the designated
// constraints aren't met.
type ResourceHandleProto_DtypeAndShapeMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ResourceHandleProto_DtypeAndShapeMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ResourceHandleProto_DtypeAndShapeMultiError) AllErrors() []error { return m }

// ResourceHandleProto_DtypeAndShapeValidationError is the validation error
// returned by ResourceHandleProto_DtypeAndShape.Validate if the designated
// constraints aren't met.
type ResourceHandleProto_DtypeAndShapeValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ResourceHandleProto_DtypeAndShapeValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ResourceHandleProto_DtypeAndShapeValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ResourceHandleProto_DtypeAndShapeValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ResourceHandleProto_DtypeAndShapeValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ResourceHandleProto_DtypeAndShapeValidationError) ErrorName() string {
	return "ResourceHandleProto_DtypeAndShapeValidationError"
}

// Error satisfies the builtin error interface
func (e ResourceHandleProto_DtypeAndShapeValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sResourceHandleProto_DtypeAndShape.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ResourceHandleProto_DtypeAndShapeValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ResourceHandleProto_DtypeAndShapeValidationError{}
