# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from . import manager_pb2 as manager__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in manager_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ManagerStub(object):
    """Manager RPC Service.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetSeedPeer = channel.unary_unary(
                '/manager.v2.Manager/GetSeedPeer',
                request_serializer=manager__pb2.GetSeedPeerRequest.SerializeToString,
                response_deserializer=manager__pb2.SeedPeer.FromString,
                _registered_method=True)
        self.ListSeedPeers = channel.unary_unary(
                '/manager.v2.Manager/ListSeedPeers',
                request_serializer=manager__pb2.ListSeedPeersRequest.SerializeToString,
                response_deserializer=manager__pb2.ListSeedPeersResponse.FromString,
                _registered_method=True)
        self.UpdateSeedPeer = channel.unary_unary(
                '/manager.v2.Manager/UpdateSeedPeer',
                request_serializer=manager__pb2.UpdateSeedPeerRequest.SerializeToString,
                response_deserializer=manager__pb2.SeedPeer.FromString,
                _registered_method=True)
        self.DeleteSeedPeer = channel.unary_unary(
                '/manager.v2.Manager/DeleteSeedPeer',
                request_serializer=manager__pb2.DeleteSeedPeerRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.GetScheduler = channel.unary_unary(
                '/manager.v2.Manager/GetScheduler',
                request_serializer=manager__pb2.GetSchedulerRequest.SerializeToString,
                response_deserializer=manager__pb2.Scheduler.FromString,
                _registered_method=True)
        self.UpdateScheduler = channel.unary_unary(
                '/manager.v2.Manager/UpdateScheduler',
                request_serializer=manager__pb2.UpdateSchedulerRequest.SerializeToString,
                response_deserializer=manager__pb2.Scheduler.FromString,
                _registered_method=True)
        self.ListSchedulers = channel.unary_unary(
                '/manager.v2.Manager/ListSchedulers',
                request_serializer=manager__pb2.ListSchedulersRequest.SerializeToString,
                response_deserializer=manager__pb2.ListSchedulersResponse.FromString,
                _registered_method=True)
        self.ListApplications = channel.unary_unary(
                '/manager.v2.Manager/ListApplications',
                request_serializer=manager__pb2.ListApplicationsRequest.SerializeToString,
                response_deserializer=manager__pb2.ListApplicationsResponse.FromString,
                _registered_method=True)
        self.KeepAlive = channel.stream_unary(
                '/manager.v2.Manager/KeepAlive',
                request_serializer=manager__pb2.KeepAliveRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)


class ManagerServicer(object):
    """Manager RPC Service.
    """

    def GetSeedPeer(self, request, context):
        """Get SeedPeer and SeedPeer cluster configuration.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSeedPeers(self, request, context):
        """List acitve schedulers configuration.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateSeedPeer(self, request, context):
        """Update SeedPeer configuration.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteSeedPeer(self, request, context):
        """Delete SeedPeer configuration.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetScheduler(self, request, context):
        """Get Scheduler and Scheduler cluster configuration.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateScheduler(self, request, context):
        """Update scheduler configuration.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSchedulers(self, request, context):
        """List acitve schedulers configuration.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListApplications(self, request, context):
        """List applications configuration.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def KeepAlive(self, request_iterator, context):
        """KeepAlive with manager.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ManagerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetSeedPeer': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSeedPeer,
                    request_deserializer=manager__pb2.GetSeedPeerRequest.FromString,
                    response_serializer=manager__pb2.SeedPeer.SerializeToString,
            ),
            'ListSeedPeers': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSeedPeers,
                    request_deserializer=manager__pb2.ListSeedPeersRequest.FromString,
                    response_serializer=manager__pb2.ListSeedPeersResponse.SerializeToString,
            ),
            'UpdateSeedPeer': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateSeedPeer,
                    request_deserializer=manager__pb2.UpdateSeedPeerRequest.FromString,
                    response_serializer=manager__pb2.SeedPeer.SerializeToString,
            ),
            'DeleteSeedPeer': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteSeedPeer,
                    request_deserializer=manager__pb2.DeleteSeedPeerRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetScheduler': grpc.unary_unary_rpc_method_handler(
                    servicer.GetScheduler,
                    request_deserializer=manager__pb2.GetSchedulerRequest.FromString,
                    response_serializer=manager__pb2.Scheduler.SerializeToString,
            ),
            'UpdateScheduler': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateScheduler,
                    request_deserializer=manager__pb2.UpdateSchedulerRequest.FromString,
                    response_serializer=manager__pb2.Scheduler.SerializeToString,
            ),
            'ListSchedulers': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSchedulers,
                    request_deserializer=manager__pb2.ListSchedulersRequest.FromString,
                    response_serializer=manager__pb2.ListSchedulersResponse.SerializeToString,
            ),
            'ListApplications': grpc.unary_unary_rpc_method_handler(
                    servicer.ListApplications,
                    request_deserializer=manager__pb2.ListApplicationsRequest.FromString,
                    response_serializer=manager__pb2.ListApplicationsResponse.SerializeToString,
            ),
            'KeepAlive': grpc.stream_unary_rpc_method_handler(
                    servicer.KeepAlive,
                    request_deserializer=manager__pb2.KeepAliveRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'manager.v2.Manager', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('manager.v2.Manager', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Manager(object):
    """Manager RPC Service.
    """

    @staticmethod
    def GetSeedPeer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/manager.v2.Manager/GetSeedPeer',
            manager__pb2.GetSeedPeerRequest.SerializeToString,
            manager__pb2.SeedPeer.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSeedPeers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/manager.v2.Manager/ListSeedPeers',
            manager__pb2.ListSeedPeersRequest.SerializeToString,
            manager__pb2.ListSeedPeersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateSeedPeer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/manager.v2.Manager/UpdateSeedPeer',
            manager__pb2.UpdateSeedPeerRequest.SerializeToString,
            manager__pb2.SeedPeer.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteSeedPeer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/manager.v2.Manager/DeleteSeedPeer',
            manager__pb2.DeleteSeedPeerRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetScheduler(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/manager.v2.Manager/GetScheduler',
            manager__pb2.GetSchedulerRequest.SerializeToString,
            manager__pb2.Scheduler.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateScheduler(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/manager.v2.Manager/UpdateScheduler',
            manager__pb2.UpdateSchedulerRequest.SerializeToString,
            manager__pb2.Scheduler.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSchedulers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/manager.v2.Manager/ListSchedulers',
            manager__pb2.ListSchedulersRequest.SerializeToString,
            manager__pb2.ListSchedulersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListApplications(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/manager.v2.Manager/ListApplications',
            manager__pb2.ListApplicationsRequest.SerializeToString,
            manager__pb2.ListApplicationsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def KeepAlive(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/manager.v2.Manager/KeepAlive',
            manager__pb2.KeepAliveRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
