# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import common_pb2 as common__pb2
from . import dfdaemon_pb2 as dfdaemon__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in dfdaemon_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DfdaemonUploadStub(object):
    """DfdaemonUpload represents upload service of dfdaemon.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DownloadTask = channel.unary_stream(
                '/dfdaemon.v2.DfdaemonUpload/DownloadTask',
                request_serializer=dfdaemon__pb2.DownloadTaskRequest.SerializeToString,
                response_deserializer=dfdaemon__pb2.DownloadTaskResponse.FromString,
                _registered_method=True)
        self.StatTask = channel.unary_unary(
                '/dfdaemon.v2.DfdaemonUpload/StatTask',
                request_serializer=dfdaemon__pb2.StatTaskRequest.SerializeToString,
                response_deserializer=common__pb2.Task.FromString,
                _registered_method=True)
        self.StatLocalTask = channel.unary_unary(
                '/dfdaemon.v2.DfdaemonUpload/StatLocalTask',
                request_serializer=dfdaemon__pb2.StatLocalTaskRequest.SerializeToString,
                response_deserializer=dfdaemon__pb2.StatLocalTaskResponse.FromString,
                _registered_method=True)
        self.ListTaskEntries = channel.unary_unary(
                '/dfdaemon.v2.DfdaemonUpload/ListTaskEntries',
                request_serializer=dfdaemon__pb2.ListTaskEntriesRequest.SerializeToString,
                response_deserializer=dfdaemon__pb2.ListTaskEntriesResponse.FromString,
                _registered_method=True)
        self.DeleteTask = channel.unary_unary(
                '/dfdaemon.v2.DfdaemonUpload/DeleteTask',
                request_serializer=dfdaemon__pb2.DeleteTaskRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.SyncPieces = channel.unary_stream(
                '/dfdaemon.v2.DfdaemonUpload/SyncPieces',
                request_serializer=dfdaemon__pb2.SyncPiecesRequest.SerializeToString,
                response_deserializer=dfdaemon__pb2.SyncPiecesResponse.FromString,
                _registered_method=True)
        self.DownloadCacheTask = channel.unary_stream(
                '/dfdaemon.v2.DfdaemonUpload/DownloadCacheTask',
                request_serializer=dfdaemon__pb2.DownloadCacheTaskRequest.SerializeToString,
                response_deserializer=dfdaemon__pb2.DownloadCacheTaskResponse.FromString,
                _registered_method=True)
        self.StatCacheTask = channel.unary_unary(
                '/dfdaemon.v2.DfdaemonUpload/StatCacheTask',
                request_serializer=dfdaemon__pb2.StatCacheTaskRequest.SerializeToString,
                response_deserializer=common__pb2.CacheTask.FromString,
                _registered_method=True)
        self.DeleteCacheTask = channel.unary_unary(
                '/dfdaemon.v2.DfdaemonUpload/DeleteCacheTask',
                request_serializer=dfdaemon__pb2.DeleteCacheTaskRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.SyncCachePieces = channel.unary_stream(
                '/dfdaemon.v2.DfdaemonUpload/SyncCachePieces',
                request_serializer=dfdaemon__pb2.SyncCachePiecesRequest.SerializeToString,
                response_deserializer=dfdaemon__pb2.SyncCachePiecesResponse.FromString,
                _registered_method=True)
        self.DownloadCachePiece = channel.unary_unary(
                '/dfdaemon.v2.DfdaemonUpload/DownloadCachePiece',
                request_serializer=dfdaemon__pb2.DownloadCachePieceRequest.SerializeToString,
                response_deserializer=dfdaemon__pb2.DownloadCachePieceResponse.FromString,
                _registered_method=True)
        self.DownloadPersistentTask = channel.unary_stream(
                '/dfdaemon.v2.DfdaemonUpload/DownloadPersistentTask',
                request_serializer=dfdaemon__pb2.DownloadPersistentTaskRequest.SerializeToString,
                response_deserializer=dfdaemon__pb2.DownloadPersistentTaskResponse.FromString,
                _registered_method=True)
        self.SyncPersistentPieces = channel.unary_stream(
                '/dfdaemon.v2.DfdaemonUpload/SyncPersistentPieces',
                request_serializer=dfdaemon__pb2.SyncPersistentPiecesRequest.SerializeToString,
                response_deserializer=dfdaemon__pb2.SyncPersistentPiecesResponse.FromString,
                _registered_method=True)
        self.UpdatePersistentTask = channel.unary_unary(
                '/dfdaemon.v2.DfdaemonUpload/UpdatePersistentTask',
                request_serializer=dfdaemon__pb2.UpdatePersistentTaskRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.StatPersistentTask = channel.unary_unary(
                '/dfdaemon.v2.DfdaemonUpload/StatPersistentTask',
                request_serializer=dfdaemon__pb2.StatPersistentTaskRequest.SerializeToString,
                response_deserializer=common__pb2.PersistentTask.FromString,
                _registered_method=True)
        self.DeletePersistentTask = channel.unary_unary(
                '/dfdaemon.v2.DfdaemonUpload/DeletePersistentTask',
                request_serializer=dfdaemon__pb2.DeletePersistentTaskRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.DownloadPersistentCacheTask = channel.unary_stream(
                '/dfdaemon.v2.DfdaemonUpload/DownloadPersistentCacheTask',
                request_serializer=dfdaemon__pb2.DownloadPersistentCacheTaskRequest.SerializeToString,
                response_deserializer=dfdaemon__pb2.DownloadPersistentCacheTaskResponse.FromString,
                _registered_method=True)
        self.UpdatePersistentCacheTask = channel.unary_unary(
                '/dfdaemon.v2.DfdaemonUpload/UpdatePersistentCacheTask',
                request_serializer=dfdaemon__pb2.UpdatePersistentCacheTaskRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.StatPersistentCacheTask = channel.unary_unary(
                '/dfdaemon.v2.DfdaemonUpload/StatPersistentCacheTask',
                request_serializer=dfdaemon__pb2.StatPersistentCacheTaskRequest.SerializeToString,
                response_deserializer=common__pb2.PersistentCacheTask.FromString,
                _registered_method=True)
        self.DeletePersistentCacheTask = channel.unary_unary(
                '/dfdaemon.v2.DfdaemonUpload/DeletePersistentCacheTask',
                request_serializer=dfdaemon__pb2.DeletePersistentCacheTaskRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.SyncPersistentCachePieces = channel.unary_stream(
                '/dfdaemon.v2.DfdaemonUpload/SyncPersistentCachePieces',
                request_serializer=dfdaemon__pb2.SyncPersistentCachePiecesRequest.SerializeToString,
                response_deserializer=dfdaemon__pb2.SyncPersistentCachePiecesResponse.FromString,
                _registered_method=True)
        self.SyncHost = channel.unary_stream(
                '/dfdaemon.v2.DfdaemonUpload/SyncHost',
                request_serializer=dfdaemon__pb2.SyncHostRequest.SerializeToString,
                response_deserializer=common__pb2.Host.FromString,
                _registered_method=True)
        self.ExchangeIBVerbsQueuePairEndpoint = channel.unary_unary(
                '/dfdaemon.v2.DfdaemonUpload/ExchangeIBVerbsQueuePairEndpoint',
                request_serializer=dfdaemon__pb2.ExchangeIBVerbsQueuePairEndpointRequest.SerializeToString,
                response_deserializer=dfdaemon__pb2.ExchangeIBVerbsQueuePairEndpointResponse.FromString,
                _registered_method=True)


class DfdaemonUploadServicer(object):
    """DfdaemonUpload represents upload service of dfdaemon.
    """

    def DownloadTask(self, request, context):
        """DownloadTask downloads task from p2p network.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StatTask(self, request, context):
        """StatTask stats task information.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StatLocalTask(self, request, context):
        """StatLocalTask stats local task information from peer.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTaskEntries(self, request, context):
        """ListTaskEntries lists task entries for downloading directory.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteTask(self, request, context):
        """DeleteTask deletes task from p2p network.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SyncPieces(self, request, context):
        """SyncPieces syncs piece metadatas from remote peer.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DownloadCacheTask(self, request, context):
        """DownloadCacheTask downloads cache task from p2p network.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StatCacheTask(self, request, context):
        """StatCacheTask stats cache task information.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteCacheTask(self, request, context):
        """DeleteCacheTask deletes cache task from p2p network.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SyncCachePieces(self, request, context):
        """SyncCachePieces syncs cache piece metadatas from remote peer.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DownloadCachePiece(self, request, context):
        """DownloadCachePiece downloads cache piece from the remote peer.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DownloadPersistentTask(self, request, context):
        """DownloadPersistentTask downloads persistent task from p2p network.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SyncPersistentPieces(self, request, context):
        """SyncPersistentPieces syncs persistent pieces from remote peer.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdatePersistentTask(self, request, context):
        """UpdatePersistentTask updates metadate of thr persistent task in p2p network.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StatPersistentTask(self, request, context):
        """StatPersistentTask stats persistent task information.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeletePersistentTask(self, request, context):
        """DeletePersistentTask deletes persistent task from p2p network.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DownloadPersistentCacheTask(self, request, context):
        """DownloadPersistentCacheTask downloads persistent cache task from p2p network.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdatePersistentCacheTask(self, request, context):
        """UpdatePersistentCacheTask updates metadate of thr persistent cache task in p2p network.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StatPersistentCacheTask(self, request, context):
        """StatPersistentCacheTask stats persistent cache task information.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeletePersistentCacheTask(self, request, context):
        """DeletePersistentCacheTask deletes persistent cache task from p2p network.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SyncPersistentCachePieces(self, request, context):
        """SyncPersistentCachePieces syncs persistent cache pieces from remote peer.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SyncHost(self, request, context):
        """SyncHost sync host info from parents.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExchangeIBVerbsQueuePairEndpoint(self, request, context):
        """ExchangeIBVerbsQueuePairEndpoint exchanges queue pair endpoint of IBVerbs with remote peer.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DfdaemonUploadServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DownloadTask': grpc.unary_stream_rpc_method_handler(
                    servicer.DownloadTask,
                    request_deserializer=dfdaemon__pb2.DownloadTaskRequest.FromString,
                    response_serializer=dfdaemon__pb2.DownloadTaskResponse.SerializeToString,
            ),
            'StatTask': grpc.unary_unary_rpc_method_handler(
                    servicer.StatTask,
                    request_deserializer=dfdaemon__pb2.StatTaskRequest.FromString,
                    response_serializer=common__pb2.Task.SerializeToString,
            ),
            'StatLocalTask': grpc.unary_unary_rpc_method_handler(
                    servicer.StatLocalTask,
                    request_deserializer=dfdaemon__pb2.StatLocalTaskRequest.FromString,
                    response_serializer=dfdaemon__pb2.StatLocalTaskResponse.SerializeToString,
            ),
            'ListTaskEntries': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTaskEntries,
                    request_deserializer=dfdaemon__pb2.ListTaskEntriesRequest.FromString,
                    response_serializer=dfdaemon__pb2.ListTaskEntriesResponse.SerializeToString,
            ),
            'DeleteTask': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteTask,
                    request_deserializer=dfdaemon__pb2.DeleteTaskRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'SyncPieces': grpc.unary_stream_rpc_method_handler(
                    servicer.SyncPieces,
                    request_deserializer=dfdaemon__pb2.SyncPiecesRequest.FromString,
                    response_serializer=dfdaemon__pb2.SyncPiecesResponse.SerializeToString,
            ),
            'DownloadCacheTask': grpc.unary_stream_rpc_method_handler(
                    servicer.DownloadCacheTask,
                    request_deserializer=dfdaemon__pb2.DownloadCacheTaskRequest.FromString,
                    response_serializer=dfdaemon__pb2.DownloadCacheTaskResponse.SerializeToString,
            ),
            'StatCacheTask': grpc.unary_unary_rpc_method_handler(
                    servicer.StatCacheTask,
                    request_deserializer=dfdaemon__pb2.StatCacheTaskRequest.FromString,
                    response_serializer=common__pb2.CacheTask.SerializeToString,
            ),
            'DeleteCacheTask': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteCacheTask,
                    request_deserializer=dfdaemon__pb2.DeleteCacheTaskRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'SyncCachePieces': grpc.unary_stream_rpc_method_handler(
                    servicer.SyncCachePieces,
                    request_deserializer=dfdaemon__pb2.SyncCachePiecesRequest.FromString,
                    response_serializer=dfdaemon__pb2.SyncCachePiecesResponse.SerializeToString,
            ),
            'DownloadCachePiece': grpc.unary_unary_rpc_method_handler(
                    servicer.DownloadCachePiece,
                    request_deserializer=dfdaemon__pb2.DownloadCachePieceRequest.FromString,
                    response_serializer=dfdaemon__pb2.DownloadCachePieceResponse.SerializeToString,
            ),
            'DownloadPersistentTask': grpc.unary_stream_rpc_method_handler(
                    servicer.DownloadPersistentTask,
                    request_deserializer=dfdaemon__pb2.DownloadPersistentTaskRequest.FromString,
                    response_serializer=dfdaemon__pb2.DownloadPersistentTaskResponse.SerializeToString,
            ),
            'SyncPersistentPieces': grpc.unary_stream_rpc_method_handler(
                    servicer.SyncPersistentPieces,
                    request_deserializer=dfdaemon__pb2.SyncPersistentPiecesRequest.FromString,
                    response_serializer=dfdaemon__pb2.SyncPersistentPiecesResponse.SerializeToString,
            ),
            'UpdatePersistentTask': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdatePersistentTask,
                    request_deserializer=dfdaemon__pb2.UpdatePersistentTaskRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'StatPersistentTask': grpc.unary_unary_rpc_method_handler(
                    servicer.StatPersistentTask,
                    request_deserializer=dfdaemon__pb2.StatPersistentTaskRequest.FromString,
                    response_serializer=common__pb2.PersistentTask.SerializeToString,
            ),
            'DeletePersistentTask': grpc.unary_unary_rpc_method_handler(
                    servicer.DeletePersistentTask,
                    request_deserializer=dfdaemon__pb2.DeletePersistentTaskRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'DownloadPersistentCacheTask': grpc.unary_stream_rpc_method_handler(
                    servicer.DownloadPersistentCacheTask,
                    request_deserializer=dfdaemon__pb2.DownloadPersistentCacheTaskRequest.FromString,
                    response_serializer=dfdaemon__pb2.DownloadPersistentCacheTaskResponse.SerializeToString,
            ),
            'UpdatePersistentCacheTask': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdatePersistentCacheTask,
                    request_deserializer=dfdaemon__pb2.UpdatePersistentCacheTaskRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'StatPersistentCacheTask': grpc.unary_unary_rpc_method_handler(
                    servicer.StatPersistentCacheTask,
                    request_deserializer=dfdaemon__pb2.StatPersistentCacheTaskRequest.FromString,
                    response_serializer=common__pb2.PersistentCacheTask.SerializeToString,
            ),
            'DeletePersistentCacheTask': grpc.unary_unary_rpc_method_handler(
                    servicer.DeletePersistentCacheTask,
                    request_deserializer=dfdaemon__pb2.DeletePersistentCacheTaskRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'SyncPersistentCachePieces': grpc.unary_stream_rpc_method_handler(
                    servicer.SyncPersistentCachePieces,
                    request_deserializer=dfdaemon__pb2.SyncPersistentCachePiecesRequest.FromString,
                    response_serializer=dfdaemon__pb2.SyncPersistentCachePiecesResponse.SerializeToString,
            ),
            'SyncHost': grpc.unary_stream_rpc_method_handler(
                    servicer.SyncHost,
                    request_deserializer=dfdaemon__pb2.SyncHostRequest.FromString,
                    response_serializer=common__pb2.Host.SerializeToString,
            ),
            'ExchangeIBVerbsQueuePairEndpoint': grpc.unary_unary_rpc_method_handler(
                    servicer.ExchangeIBVerbsQueuePairEndpoint,
                    request_deserializer=dfdaemon__pb2.ExchangeIBVerbsQueuePairEndpointRequest.FromString,
                    response_serializer=dfdaemon__pb2.ExchangeIBVerbsQueuePairEndpointResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dfdaemon.v2.DfdaemonUpload', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dfdaemon.v2.DfdaemonUpload', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DfdaemonUpload(object):
    """DfdaemonUpload represents upload service of dfdaemon.
    """

    @staticmethod
    def DownloadTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/dfdaemon.v2.DfdaemonUpload/DownloadTask',
            dfdaemon__pb2.DownloadTaskRequest.SerializeToString,
            dfdaemon__pb2.DownloadTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StatTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dfdaemon.v2.DfdaemonUpload/StatTask',
            dfdaemon__pb2.StatTaskRequest.SerializeToString,
            common__pb2.Task.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StatLocalTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dfdaemon.v2.DfdaemonUpload/StatLocalTask',
            dfdaemon__pb2.StatLocalTaskRequest.SerializeToString,
            dfdaemon__pb2.StatLocalTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListTaskEntries(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dfdaemon.v2.DfdaemonUpload/ListTaskEntries',
            dfdaemon__pb2.ListTaskEntriesRequest.SerializeToString,
            dfdaemon__pb2.ListTaskEntriesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dfdaemon.v2.DfdaemonUpload/DeleteTask',
            dfdaemon__pb2.DeleteTaskRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SyncPieces(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/dfdaemon.v2.DfdaemonUpload/SyncPieces',
            dfdaemon__pb2.SyncPiecesRequest.SerializeToString,
            dfdaemon__pb2.SyncPiecesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DownloadCacheTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/dfdaemon.v2.DfdaemonUpload/DownloadCacheTask',
            dfdaemon__pb2.DownloadCacheTaskRequest.SerializeToString,
            dfdaemon__pb2.DownloadCacheTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StatCacheTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dfdaemon.v2.DfdaemonUpload/StatCacheTask',
            dfdaemon__pb2.StatCacheTaskRequest.SerializeToString,
            common__pb2.CacheTask.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteCacheTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dfdaemon.v2.DfdaemonUpload/DeleteCacheTask',
            dfdaemon__pb2.DeleteCacheTaskRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SyncCachePieces(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/dfdaemon.v2.DfdaemonUpload/SyncCachePieces',
            dfdaemon__pb2.SyncCachePiecesRequest.SerializeToString,
            dfdaemon__pb2.SyncCachePiecesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DownloadCachePiece(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dfdaemon.v2.DfdaemonUpload/DownloadCachePiece',
            dfdaemon__pb2.DownloadCachePieceRequest.SerializeToString,
            dfdaemon__pb2.DownloadCachePieceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DownloadPersistentTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/dfdaemon.v2.DfdaemonUpload/DownloadPersistentTask',
            dfdaemon__pb2.DownloadPersistentTaskRequest.SerializeToString,
            dfdaemon__pb2.DownloadPersistentTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SyncPersistentPieces(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/dfdaemon.v2.DfdaemonUpload/SyncPersistentPieces',
            dfdaemon__pb2.SyncPersistentPiecesRequest.SerializeToString,
            dfdaemon__pb2.SyncPersistentPiecesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdatePersistentTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dfdaemon.v2.DfdaemonUpload/UpdatePersistentTask',
            dfdaemon__pb2.UpdatePersistentTaskRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StatPersistentTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dfdaemon.v2.DfdaemonUpload/StatPersistentTask',
            dfdaemon__pb2.StatPersistentTaskRequest.SerializeToString,
            common__pb2.PersistentTask.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeletePersistentTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dfdaemon.v2.DfdaemonUpload/DeletePersistentTask',
            dfdaemon__pb2.DeletePersistentTaskRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DownloadPersistentCacheTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/dfdaemon.v2.DfdaemonUpload/DownloadPersistentCacheTask',
            dfdaemon__pb2.DownloadPersistentCacheTaskRequest.SerializeToString,
            dfdaemon__pb2.DownloadPersistentCacheTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdatePersistentCacheTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dfdaemon.v2.DfdaemonUpload/UpdatePersistentCacheTask',
            dfdaemon__pb2.UpdatePersistentCacheTaskRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StatPersistentCacheTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dfdaemon.v2.DfdaemonUpload/StatPersistentCacheTask',
            dfdaemon__pb2.StatPersistentCacheTaskRequest.SerializeToString,
            common__pb2.PersistentCacheTask.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeletePersistentCacheTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dfdaemon.v2.DfdaemonUpload/DeletePersistentCacheTask',
            dfdaemon__pb2.DeletePersistentCacheTaskRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SyncPersistentCachePieces(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/dfdaemon.v2.DfdaemonUpload/SyncPersistentCachePieces',
            dfdaemon__pb2.SyncPersistentCachePiecesRequest.SerializeToString,
            dfdaemon__pb2.SyncPersistentCachePiecesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SyncHost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/dfdaemon.v2.DfdaemonUpload/SyncHost',
            dfdaemon__pb2.SyncHostRequest.SerializeToString,
            common__pb2.Host.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExchangeIBVerbsQueuePairEndpoint(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dfdaemon.v2.DfdaemonUpload/ExchangeIBVerbsQueuePairEndpoint',
            dfdaemon__pb2.ExchangeIBVerbsQueuePairEndpointRequest.SerializeToString,
            dfdaemon__pb2.ExchangeIBVerbsQueuePairEndpointResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class DfdaemonDownloadStub(object):
    """DfdaemonDownload represents download service of dfdaemon.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DownloadTask = channel.unary_stream(
                '/dfdaemon.v2.DfdaemonDownload/DownloadTask',
                request_serializer=dfdaemon__pb2.DownloadTaskRequest.SerializeToString,
                response_deserializer=dfdaemon__pb2.DownloadTaskResponse.FromString,
                _registered_method=True)
        self.StatTask = channel.unary_unary(
                '/dfdaemon.v2.DfdaemonDownload/StatTask',
                request_serializer=dfdaemon__pb2.StatTaskRequest.SerializeToString,
                response_deserializer=common__pb2.Task.FromString,
                _registered_method=True)
        self.StatLocalTask = channel.unary_unary(
                '/dfdaemon.v2.DfdaemonDownload/StatLocalTask',
                request_serializer=dfdaemon__pb2.StatLocalTaskRequest.SerializeToString,
                response_deserializer=dfdaemon__pb2.StatLocalTaskResponse.FromString,
                _registered_method=True)
        self.ListTaskEntries = channel.unary_unary(
                '/dfdaemon.v2.DfdaemonDownload/ListTaskEntries',
                request_serializer=dfdaemon__pb2.ListTaskEntriesRequest.SerializeToString,
                response_deserializer=dfdaemon__pb2.ListTaskEntriesResponse.FromString,
                _registered_method=True)
        self.DeleteTask = channel.unary_unary(
                '/dfdaemon.v2.DfdaemonDownload/DeleteTask',
                request_serializer=dfdaemon__pb2.DeleteTaskRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.DeleteHost = channel.unary_unary(
                '/dfdaemon.v2.DfdaemonDownload/DeleteHost',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.DownloadCacheTask = channel.unary_stream(
                '/dfdaemon.v2.DfdaemonDownload/DownloadCacheTask',
                request_serializer=dfdaemon__pb2.DownloadCacheTaskRequest.SerializeToString,
                response_deserializer=dfdaemon__pb2.DownloadCacheTaskResponse.FromString,
                _registered_method=True)
        self.StatCacheTask = channel.unary_unary(
                '/dfdaemon.v2.DfdaemonDownload/StatCacheTask',
                request_serializer=dfdaemon__pb2.StatCacheTaskRequest.SerializeToString,
                response_deserializer=common__pb2.CacheTask.FromString,
                _registered_method=True)
        self.DeleteCacheTask = channel.unary_unary(
                '/dfdaemon.v2.DfdaemonDownload/DeleteCacheTask',
                request_serializer=dfdaemon__pb2.DeleteCacheTaskRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.DownloadPersistentTask = channel.unary_stream(
                '/dfdaemon.v2.DfdaemonDownload/DownloadPersistentTask',
                request_serializer=dfdaemon__pb2.DownloadPersistentTaskRequest.SerializeToString,
                response_deserializer=dfdaemon__pb2.DownloadPersistentTaskResponse.FromString,
                _registered_method=True)
        self.UploadPersistentTask = channel.unary_unary(
                '/dfdaemon.v2.DfdaemonDownload/UploadPersistentTask',
                request_serializer=dfdaemon__pb2.UploadPersistentTaskRequest.SerializeToString,
                response_deserializer=common__pb2.PersistentTask.FromString,
                _registered_method=True)
        self.DownloadPersistentCacheTask = channel.unary_stream(
                '/dfdaemon.v2.DfdaemonDownload/DownloadPersistentCacheTask',
                request_serializer=dfdaemon__pb2.DownloadPersistentCacheTaskRequest.SerializeToString,
                response_deserializer=dfdaemon__pb2.DownloadPersistentCacheTaskResponse.FromString,
                _registered_method=True)
        self.UploadPersistentCacheTask = channel.unary_unary(
                '/dfdaemon.v2.DfdaemonDownload/UploadPersistentCacheTask',
                request_serializer=dfdaemon__pb2.UploadPersistentCacheTaskRequest.SerializeToString,
                response_deserializer=common__pb2.PersistentCacheTask.FromString,
                _registered_method=True)
        self.StatPersistentCacheTask = channel.unary_unary(
                '/dfdaemon.v2.DfdaemonDownload/StatPersistentCacheTask',
                request_serializer=dfdaemon__pb2.StatPersistentCacheTaskRequest.SerializeToString,
                response_deserializer=common__pb2.PersistentCacheTask.FromString,
                _registered_method=True)


class DfdaemonDownloadServicer(object):
    """DfdaemonDownload represents download service of dfdaemon.
    """

    def DownloadTask(self, request, context):
        """DownloadTask downloads task from p2p network.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StatTask(self, request, context):
        """StatTask stats task information.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StatLocalTask(self, request, context):
        """StatLocalTask stats local task information from peer.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTaskEntries(self, request, context):
        """ListTaskEntries lists task entries for downloading directory.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteTask(self, request, context):
        """DeleteTask deletes task from p2p network.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteHost(self, request, context):
        """DeleteHost releases host in scheduler.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DownloadCacheTask(self, request, context):
        """DownloadCacheTask downloads cache task from p2p network.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StatCacheTask(self, request, context):
        """StatCacheTask stats cache task information.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteCacheTask(self, request, context):
        """DeleteCacheTask deletes cache task from p2p network.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DownloadPersistentTask(self, request, context):
        """DownloadPersistentTask downloads persistent task from p2p network.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadPersistentTask(self, request, context):
        """UploadPersistentTask uploads persistent task to p2p network.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DownloadPersistentCacheTask(self, request, context):
        """DownloadPersistentCacheTask downloads persistent cache task from p2p network.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadPersistentCacheTask(self, request, context):
        """UploadPersistentCacheTask uploads persistent cache task to p2p network.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StatPersistentCacheTask(self, request, context):
        """StatPersistentCacheTask stats persistent cache task information.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DfdaemonDownloadServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DownloadTask': grpc.unary_stream_rpc_method_handler(
                    servicer.DownloadTask,
                    request_deserializer=dfdaemon__pb2.DownloadTaskRequest.FromString,
                    response_serializer=dfdaemon__pb2.DownloadTaskResponse.SerializeToString,
            ),
            'StatTask': grpc.unary_unary_rpc_method_handler(
                    servicer.StatTask,
                    request_deserializer=dfdaemon__pb2.StatTaskRequest.FromString,
                    response_serializer=common__pb2.Task.SerializeToString,
            ),
            'StatLocalTask': grpc.unary_unary_rpc_method_handler(
                    servicer.StatLocalTask,
                    request_deserializer=dfdaemon__pb2.StatLocalTaskRequest.FromString,
                    response_serializer=dfdaemon__pb2.StatLocalTaskResponse.SerializeToString,
            ),
            'ListTaskEntries': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTaskEntries,
                    request_deserializer=dfdaemon__pb2.ListTaskEntriesRequest.FromString,
                    response_serializer=dfdaemon__pb2.ListTaskEntriesResponse.SerializeToString,
            ),
            'DeleteTask': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteTask,
                    request_deserializer=dfdaemon__pb2.DeleteTaskRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'DeleteHost': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteHost,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'DownloadCacheTask': grpc.unary_stream_rpc_method_handler(
                    servicer.DownloadCacheTask,
                    request_deserializer=dfdaemon__pb2.DownloadCacheTaskRequest.FromString,
                    response_serializer=dfdaemon__pb2.DownloadCacheTaskResponse.SerializeToString,
            ),
            'StatCacheTask': grpc.unary_unary_rpc_method_handler(
                    servicer.StatCacheTask,
                    request_deserializer=dfdaemon__pb2.StatCacheTaskRequest.FromString,
                    response_serializer=common__pb2.CacheTask.SerializeToString,
            ),
            'DeleteCacheTask': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteCacheTask,
                    request_deserializer=dfdaemon__pb2.DeleteCacheTaskRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'DownloadPersistentTask': grpc.unary_stream_rpc_method_handler(
                    servicer.DownloadPersistentTask,
                    request_deserializer=dfdaemon__pb2.DownloadPersistentTaskRequest.FromString,
                    response_serializer=dfdaemon__pb2.DownloadPersistentTaskResponse.SerializeToString,
            ),
            'UploadPersistentTask': grpc.unary_unary_rpc_method_handler(
                    servicer.UploadPersistentTask,
                    request_deserializer=dfdaemon__pb2.UploadPersistentTaskRequest.FromString,
                    response_serializer=common__pb2.PersistentTask.SerializeToString,
            ),
            'DownloadPersistentCacheTask': grpc.unary_stream_rpc_method_handler(
                    servicer.DownloadPersistentCacheTask,
                    request_deserializer=dfdaemon__pb2.DownloadPersistentCacheTaskRequest.FromString,
                    response_serializer=dfdaemon__pb2.DownloadPersistentCacheTaskResponse.SerializeToString,
            ),
            'UploadPersistentCacheTask': grpc.unary_unary_rpc_method_handler(
                    servicer.UploadPersistentCacheTask,
                    request_deserializer=dfdaemon__pb2.UploadPersistentCacheTaskRequest.FromString,
                    response_serializer=common__pb2.PersistentCacheTask.SerializeToString,
            ),
            'StatPersistentCacheTask': grpc.unary_unary_rpc_method_handler(
                    servicer.StatPersistentCacheTask,
                    request_deserializer=dfdaemon__pb2.StatPersistentCacheTaskRequest.FromString,
                    response_serializer=common__pb2.PersistentCacheTask.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dfdaemon.v2.DfdaemonDownload', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dfdaemon.v2.DfdaemonDownload', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DfdaemonDownload(object):
    """DfdaemonDownload represents download service of dfdaemon.
    """

    @staticmethod
    def DownloadTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/dfdaemon.v2.DfdaemonDownload/DownloadTask',
            dfdaemon__pb2.DownloadTaskRequest.SerializeToString,
            dfdaemon__pb2.DownloadTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StatTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dfdaemon.v2.DfdaemonDownload/StatTask',
            dfdaemon__pb2.StatTaskRequest.SerializeToString,
            common__pb2.Task.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StatLocalTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dfdaemon.v2.DfdaemonDownload/StatLocalTask',
            dfdaemon__pb2.StatLocalTaskRequest.SerializeToString,
            dfdaemon__pb2.StatLocalTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListTaskEntries(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dfdaemon.v2.DfdaemonDownload/ListTaskEntries',
            dfdaemon__pb2.ListTaskEntriesRequest.SerializeToString,
            dfdaemon__pb2.ListTaskEntriesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dfdaemon.v2.DfdaemonDownload/DeleteTask',
            dfdaemon__pb2.DeleteTaskRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteHost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dfdaemon.v2.DfdaemonDownload/DeleteHost',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DownloadCacheTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/dfdaemon.v2.DfdaemonDownload/DownloadCacheTask',
            dfdaemon__pb2.DownloadCacheTaskRequest.SerializeToString,
            dfdaemon__pb2.DownloadCacheTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StatCacheTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dfdaemon.v2.DfdaemonDownload/StatCacheTask',
            dfdaemon__pb2.StatCacheTaskRequest.SerializeToString,
            common__pb2.CacheTask.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteCacheTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dfdaemon.v2.DfdaemonDownload/DeleteCacheTask',
            dfdaemon__pb2.DeleteCacheTaskRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DownloadPersistentTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/dfdaemon.v2.DfdaemonDownload/DownloadPersistentTask',
            dfdaemon__pb2.DownloadPersistentTaskRequest.SerializeToString,
            dfdaemon__pb2.DownloadPersistentTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UploadPersistentTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dfdaemon.v2.DfdaemonDownload/UploadPersistentTask',
            dfdaemon__pb2.UploadPersistentTaskRequest.SerializeToString,
            common__pb2.PersistentTask.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DownloadPersistentCacheTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/dfdaemon.v2.DfdaemonDownload/DownloadPersistentCacheTask',
            dfdaemon__pb2.DownloadPersistentCacheTaskRequest.SerializeToString,
            dfdaemon__pb2.DownloadPersistentCacheTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UploadPersistentCacheTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dfdaemon.v2.DfdaemonDownload/UploadPersistentCacheTask',
            dfdaemon__pb2.UploadPersistentCacheTaskRequest.SerializeToString,
            common__pb2.PersistentCacheTask.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StatPersistentCacheTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dfdaemon.v2.DfdaemonDownload/StatPersistentCacheTask',
            dfdaemon__pb2.StatPersistentCacheTaskRequest.SerializeToString,
            common__pb2.PersistentCacheTask.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
